### ISSUE TITLE
    failed to send message: signal-cli execution error: Missing required native library dependency: libsignal-client

### ISSUE THREAD

**Issue by micah** [dadevel/alertmanager-signal-receiver#5]
I am building the container based on what is here, but something perhaps changed with one of the images, because when I try and send a message now, I get this:

```
message:
    error while handling request: %!w(*fmt.wrapError=&{failed to send message: signal-cli execution error: Missing required native library dependency: libsignal-client
```

**Comment by dadevel** [comment]
I will have a look this evening.

**Comment by dadevel** [comment]
signal-cli got two new dependencies: libsignal-client and libzkgroup, see AsamK/signal-cli#643 and [github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal](https://github.com/AsamK/signal-cli/wiki/Provide-native-lib-for-libsignal).
I'll switch to the [pre-built signal-cli releases](https://github.com/AsamK/signal-cli/releases). They already include these libraries but compiled for libc. So from now on I'll use Debian as base for the docker image.

**Comment by micah** [comment]
I just was trying to track down the issue. I noticed that the dockerhub image you pushed 3 days ago at dadevel/prometheus-signal-receiver:latest does work, but if I try and build it myself from this source, it does not.

I see that these issues you linked to just appeared two days ago, so that could explain it!

**Comment by dadevel** [comment]
The new `Dockerfile` should work, but the image is not updated yet.

**Comment by dadevel** [comment]
An updated image is now available as `ghcr.io/dadevel/alertmanager-signal-receiver:1.3.0`.

**Comment by micah** [comment]
I just built this locally, and tested it. It works! Impressive @dadevel !

**Comment by fabsau** [comment]
Hi sorry to bother, I am trying to setup this application and you recently moved your docker repo and I think ever since the error came back:
signal-cli: command execution failed: WARN ServiceConfig - Failed to call libsignal-client: /tmp/resource16633489847235456264.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/resource16633489847235456264.so)
Missing required native library dependency: libsignal-client
: exit status 1

I am using the image "ghcr.io/dadevel/signal-receiver:latest"

Kuss auf die Nuss und vielen Dank im Voraus
fabsau

**Comment by dadevel** [comment]
Sorry about that. Fixed again.
